### PR TITLE
Added hevelop/transliteration

### PR DESCRIPTION
**Pull request by bordeo**
https://github.com/Hevelop/Transliteration

### CODE REVIEW

**Comment by bordeo** [comment]
What is the problem with composer.json?

**Comment by daim2k5** [comment]
nothing but the entry is wrong

git@github.com:hevelop/transliteration.git WRONG
git://github.com/defactodesign/adminfirewall.git RIGHT

**Comment by bordeo** [comment]
Sorry, i correct suddenly

**Comment by bordeo** [comment]
@daim2k5 now is ok.

**Pull request closed without merging**
