### PR TITLE
 Added Magento-Two-factor-Authentication 

### PR DESCRIPTION
**Pull request by avoelkl**

### CODE REVIEW

**Comment by daim2k5** [comment]
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.magento-hackathon/magento-composer-installer : unbound version constraints (*) should be avoided

**Comment by avoelkl** [comment]
There is a LICENSE file in both of them with The MIT License (MIT).
An updated README where the license is also in will follow later in both of the repositories.
Something else I am missing here?

**Comment by avoelkl** [comment]
I saw it was missing in the composer.json files. Added it to the PR.

**Comment by daim2k5** [comment]
thanks @avoelkl

**Pull request merged**
