### PR TITLE
Added the Shopymind extension

### PR DESCRIPTION
**Pull request by real34**
Composer has just been added in the develop branch (for the next minor extension release). See https://github.com/occitech/Occitech_ShopyMind/tree/develop

### CODE REVIEW

**Comment by daim2k5** [comment]
I think the composer.json needs also be in the master branch. Sorry for the delay

**Comment by real34** [comment]
No problem, I understand. I will send an update here as soon as the next release is done.

**Comment by real34** [comment]
You can merge it now... I forgot to comment the PR again. Do you want me to reopen another one?

**Comment by daim2k5** [comment]
please make a new PR

**Pull request closed without merging**
