### PR TITLE
remove our modules

### PR DESCRIPTION
**Pull request by luckyraul**

### CODE REVIEW

**Comment by daim2k5** [comment]
@luckyraul can i ask why?

**Comment by luckyraul** [comment]
@daim2k5 

- No repository updates for 5 days 
- No download statistics
- They are all in the packagist

**Comment by daim2k5** [comment]
Thanks i did'nt saw that we got again an error on updating the list. I'm working on it. Because nobody is hurt if the packages are still listed here i like to keep them.

**Comment by luckyraul** [comment]
The main problem - If I have any extension from this repository **all my other extensions** in composer will download from  this repository. Most of the cases I need to wait until your cron updates the repository.

There are no problems with removing our extensions because they are all in packagist the very same name.

**Comment by luckyraul** [comment]
Still not updated

**Pull request merged**
