### PR TITLE
Add Arena.pl magento module

### PR DESCRIPTION
**Pull request by spiechu**

### CODE REVIEW

**Comment by spiechu** [comment]
Any clues why is it failing?
My Composer validator says _"require.magento-hackathon/magento-composer-installer : unbound version constraints (*) should be avoided"_

**Comment by daim2k5** [comment]
Sorry my script did't work but you are right your composer.json is valid. Thanks for your contribution

**Comment by spiechu** [comment]
@daim2k5 Thx for merge.
Should I require `magento-composer-installer` or only suggest it in my `composer.json`?

**Comment by daim2k5** [comment]
@spiechu suggest is better

**Pull request merged**
